"""App entrypoint. Run locally with:  uvicorn app.main:app --reload

Interactive API docs (auto-generated by FastAPI): http://127.0.0.1:8000/docs

The exported `app` is a Socket.io ASGI app wrapping the FastAPI app — one process
serves both plain HTTP routes and the /socket.io/ realtime endpoint used by the
live game board (see app/sockets.py). Everything under routes/ is unaffected;
FastAPI still handles it exactly as before.
"""

from contextlib import asynccontextmanager

import socketio
from fastapi import FastAPI

from .db import init_db
from .routes import admin, auth, debug, gameplay, games, leaderboard, users
from .seed import seed_admin
from .sockets import sio


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Runs once at startup, before serving any requests.
    init_db()
    seed_admin()
    yield


fastapi_app = FastAPI(title="Codec Ludo", lifespan=lifespan)

fastapi_app.include_router(auth.router)
fastapi_app.include_router(admin.router)
fastapi_app.include_router(users.router)
fastapi_app.include_router(games.router)
fastapi_app.include_router(gameplay.router)
fastapi_app.include_router(leaderboard.router)
fastapi_app.include_router(debug.router)  # TESTING ONLY — see routes/debug.py


@fastapi_app.get("/health", tags=["meta"])
def health():
    """Simple liveness check — also what uptime monitors can ping."""
    return {"status": "ok"}


app = socketio.ASGIApp(sio, other_asgi_app=fastapi_app)
