/* Maps the backend's abstract token positions (see backend/app/ludo.py) onto
 * cells of a classic 15x15 Ludo board, so <GamePage> can just ask "where does
 * this token render" without knowing any board geometry itself.
 *
 * Only Red's own arm/home-column is hand-placed below. The other three colors
 * are generated by rotating Red's cells 90° at a time around the board
 * center — the board has exact 4-fold rotational symmetry, so this guarantees
 * the other three corners line up correctly by construction, instead of
 * risking a transcription mistake hand-typing four near-identical sets of
 * coordinates.
 *
 * Every token — whether parked in a yard or out on the track — gets a
 * position through the *same* function, tokenPercent(), returning board-wide
 * percentages. That's deliberate: a single positioning system means a token
 * leaving its yard and a token moving along the track are the same kind of
 * update from React's perspective, so a plain CSS transition on left/top is
 * enough to make every move glide instead of jump — including yard exits and
 * captures sending a token back home.
 */

const N = 15 // the board is an N x N grid, 0-indexed
export const CELL_PCT = 100 / N

function rotate90CW([r, c]) {
  return [c, N - 1 - r]
}

function rotateTimes(coord, times) {
  let c = coord
  for (let i = 0; i < times; i++) c = rotate90CW(c)
  return c
}

// Red's home yard occupies the top-left 6x6 corner (rows/cols 0-5). This is
// Red's 13-cell stretch of the 52-square shared track — global squares 0-12,
// matching ENTRY_SQUARE[red] = 0 in the backend.
const RED_ARM = [
  [6, 1], [6, 2], [6, 3], [6, 4], [6, 5],
  [5, 6], [4, 6], [3, 6], [2, 6], [1, 6], [0, 6],
  [0, 7],
  [0, 8],
]

// Red's private 6-square home column (local positions 51-56), running from the
// edge of the board to the center square.
const RED_HOME_COLUMN = [[7, 1], [7, 2], [7, 3], [7, 4], [7, 5], [7, 6]]

export const COLORS = ['red', 'green', 'yellow', 'blue']

// global square index -> [row, col], indices 0-51, built by rotating Red's arm
// once per color in COLOR_ORDER — exactly mirrors the backend's
// ENTRY_SQUARE = {red: 0, green: 13, yellow: 26, blue: 39}.
export const SQUARE_COORDS = []
COLORS.forEach((_, colorIndex) => {
  RED_ARM.forEach((coord) => SQUARE_COORDS.push(rotateTimes(coord, colorIndex)))
})

export const HOME_COLUMN_COORDS = {}
COLORS.forEach((color, i) => {
  HOME_COLUMN_COORDS[color] = RED_HOME_COLUMN.map((c) => rotateTimes(c, i))
})

// The full 6x6 corner block each color's yard occupies (for the background
// color of the base grid — separate from the white "token card" drawn over it).
const RED_YARD_BLOCK = []
for (let r = 0; r < 6; r++) for (let c = 0; c < 6; c++) RED_YARD_BLOCK.push([r, c])

export const YARD_BLOCK_COORDS = {}
COLORS.forEach((color, i) => {
  YARD_BLOCK_COORDS[color] = RED_YARD_BLOCK.map((c) => rotateTimes(c, i))
})

// Top-left [row, col] of each color's 6x6 yard block.
export const YARD_ORIGIN = {}
COLORS.forEach((color) => {
  const rows = YARD_BLOCK_COORDS[color].map(([r]) => r)
  const cols = YARD_BLOCK_COORDS[color].map(([, c]) => c)
  YARD_ORIGIN[color] = [Math.min(...rows), Math.min(...cols)]
})

// Which color's home column approaches the center from which side — feeds the
// center pinwheel decoration. (Verified against HOME_COLUMN_COORDS: green's
// column runs down to (6,7) just above center, red's runs right to (7,6) just
// left of center, yellow's to (7,8) just right, blue's to (8,7) just below.)
export const CENTER_PINWHEEL_ORDER = ['green', 'yellow', 'blue', 'red'] // top, right, bottom, left

// Same 8 safe squares as the backend's SAFE_SQUARES (each color's entry + the
// star square 8 steps into its arm) — used only to draw a star marker.
export const SAFE_SQUARE_INDICES = new Set(
  COLORS.flatMap((_, i) => [i * 13, i * 13 + 8]),
)

/** A 15x15 array of cell descriptors, precomputed once, so <GamePage> can just
 * render `grid[r][c]` without re-deriving what each cell is. */
export function buildCellGrid() {
  const grid = Array.from({ length: N }, () => Array.from({ length: N }, () => ({ type: 'filler' })))

  COLORS.forEach((color) => {
    for (const [r, c] of YARD_BLOCK_COORDS[color]) grid[r][c] = { type: 'yard', color }
  })
  SQUARE_COORDS.forEach(([r, c], index) => {
    grid[r][c] = { type: 'track', safe: SAFE_SQUARE_INDICES.has(index) }
  })
  COLORS.forEach((color) => {
    for (const [r, c] of HOME_COLUMN_COORDS[color]) grid[r][c] = { type: 'home', color }
  })

  return grid
}

// How much of each 6-cell yard stays as visible colored margin around the
// white token card — kept as one named constant so the card and its 4 token
// slots are computed from the same source of truth and can't drift out of
// sync with each other. A bigger margin means a smaller, more generously
// bordered card (tuned down after feedback that a tighter margin made the
// card look oversized for just 4 pieces).
const YARD_CARD_MARGIN_CELLS = 1.05

/** The white "token card" for one color's yard, in board-wide percentages. */
export function yardCardRect(color) {
  const [r0, c0] = YARD_ORIGIN[color]
  const size = (6 - 2 * YARD_CARD_MARGIN_CELLS) * CELL_PCT
  return {
    left: (c0 + YARD_CARD_MARGIN_CELLS) * CELL_PCT,
    top: (r0 + YARD_CARD_MARGIN_CELLS) * CELL_PCT,
    size,
  }
}

// Where each of a card's 4 quadrants centers, as a fraction of the card's own
// width/height — a plain 2x2 layout with even margins on all sides.
const YARD_SLOT_FRACTIONS = [
  [0.28, 0.28],
  [0.72, 0.28],
  [0.28, 0.72],
  [0.72, 0.72],
]

/** Where one of a color's 4 yard slots sits, in board-wide percentages. Also
 * used directly by GamePage to build a capture's "run back home" animation
 * path, alongside trackPercent() below. */
export function yardSlotPercent(color, index) {
  const { left, top, size } = yardCardRect(color)
  const [fx, fy] = YARD_SLOT_FRACTIONS[index]
  return { left: left + size * fx, top: top + size * fy }
}

/** Where an on-track (0-56) position sits, in board-wide percentages. Exported
 * so GamePage can build a token's full step-by-step path — the intermediate
 * cells a move actually passes through — rather than a straight line between
 * only the start and end. */
export function trackPercent(color, position) {
  const [r, c] = trackCell(color, position)
  return { left: (c + 0.5) * CELL_PCT, top: (r + 0.5) * CELL_PCT }
}

/** Where a token at this color + position sits on the board, as [row, col].
 * Only meaningful for on-track positions (0-56) — yard tokens (-1) have no
 * single cell, since which of the 4 yard slots they use depends on their
 * index; use tokenPercent() below for a position that covers both cases. */
export function trackCell(color, position) {
  if (position === -1) return null
  if (position <= 50) {
    const entryIndex = COLORS.indexOf(color) * 13
    return SQUARE_COORDS[(entryIndex + position) % 52]
  }
  return HOME_COLUMN_COORDS[color][position - 51]
}

/** Board-wide {left, top} percentages for any token, yard or track — the one
 * function GamePage needs to know where to draw a token. */
export function tokenPercent(token) {
  if (token.position === -1) return yardSlotPercent(token.color, token.index)
  return trackPercent(token.color, token.position)
}

// Tailwind-friendly hex values for each color, used for yard backgrounds,
// token fills, and the turn panel.
export const COLOR_HEX = {
  red: '#e64545',
  green: '#2f9e44',
  yellow: '#f2b705',
  blue: '#2e6fd8',
}
